export const CITIES = [
    {
        id: "melbourne",
        name: "Melbourne",
        flag: "🦘",
        lat: -37.8136,
        lng: 144.9631,
        zoom: 13,
    },
    {
        id: "sydney",
        name: "Sydney",
        flag: "🌉",
        lat: -33.8688,
        lng: 151.2093,
        zoom: 13,
    },
    {
        id: "brisbane",
        name: "Brisbane",
        flag: "🌞",
        lat: -27.4698,
        lng: 153.0251,
        zoom: 13,
    },
    {
        id: "perth",
        name: "Perth",
        flag: "🌊",
        lat: -31.9505,
        lng: 115.8605,
        zoom: 13,
    },
    {
        id: "adelaide",
        name: "Adelaide",
        flag: "🍷",
        lat: -34.9285,
        lng: 138.6007,
        zoom: 13,
    },
    {
        id: "custom",
        name: "Custom Location",
        flag: "📌",
        lat: -25.2744,
        lng: 133.7751,
        zoom: 5,
    },
];